### ISSUE TITLE
Add support for self-signed TLS certs

### ISSUE THREAD

**Issue by cyberbliss** [rode/grafeas-elasticsearch#53]
I've just been testing against an Elastic instance, hosted by Kubernetes, that was created using the community elastic-operator. By default the instance only allows TLS access and it generates self-signed certs to support this. The code in the current createESClient function fails when trying to create a new ES client due to an x509 error caused by these self-signed certs, however, it was fairly straight-forward to handle this by changing the code in the function to alter the ES config and set InsecureSkipVerify to true.
What are your thoughts about a more permanent fix with a flag to enable/disable support for self-signed certs (default false)?

**Comment by aalsabag** [comment]
@cyberbliss thanks for bringing this to our attention. I didn't realize the elastic operator was secure by default.

I think a flag like this would be useful. Can you let me know if the linked branch above addresses your issue. I can raise a PR and have the team review it and see what they think.

**Comment by cyberbliss** [comment]
@aalsabag Just tested the linked branch and it works as expected. Many thanks

**Comment by aalsabag** [comment]
@cyberbliss I'm closing this issue as this was resolved by #54
