### ISSUE TITLE
Order of operations in filtering

### ISSUE THREAD

**Issue by pickjasmine** [rode/grafeas-elasticsearch#86]
can we specify parentheses around a statement (like happening in searching for resources) so we can do filtering like`name && (type1 ||type 2)`

**Comment by mrparkers** [comment]
Looks like parens are already supported by the filtering package.  Turns out `cel` will handle this for us when parsing the expression.  For example, this filter on `ListOccurrences` produces what you'd probably expect:

```
"resource.uri".startsWith("git") && ("kind" == "DISCOVERY" || "kind" == "BUILD")
```
